# Pandas: Why do we need it when we already have NumPy?
# -----------------------------------------------------
# NumPy arrays are excellent for numerical, homogeneous data (all values of the same type).
# However, real-world datasets—such as those in Excel sheets, CSVs, SQL tables—are typically
# *tabular* and *heterogeneous* (different column types: names, dates, numbers, categories).
#
# Pandas provides data structures (Series, DataFrame) that allow:
# - labeled rows and columns,
# - easier data cleaning,
# - handling of mixed datatypes,
# - loading/saving data from multiple file formats,
# - powerful indexing and slicing.
#
# In short: Pandas is designed for *data analysis*, while NumPy is designed for *numerical computation*.


import pandas as pd     # Pandas: handles structured/tabular data efficiently
import numpy as np      # NumPy: optimized for numerical, homogeneous data storage


# -----------------------------------------------------------------------------
# Pandas Data Structures
# 1) Series     -> 1-dimensional labeled array
# 2) DataFrame  -> 2-dimensional labeled table
# -----------------------------------------------------------------------------


# -------------------------
# Creating a Series from a list
# -------------------------
river = ['ganga', 'yamuna', 'neil', 'Tennessee', 'Brazos']
print(river, type(river))  # Normal Python list

# Convert list to Pandas Series
print(pd.Series(river))
# Note: Pandas automatically assigns integer index (0, 1, 2, ...)


# -------------------------
# Creating a Series from NumPy array
# -------------------------
print(pd.Series(np.random.randn(5)))
# Here, a Series is created from random numbers generated by NumPy.


# -------------------------
# Creating a Series from a Dictionary
# -------------------------
dic = {'a': 1, 'b': 2, 'c': 3}
print(pd.Series(dic))
# When using a dictionary:
# - Dictionary keys become the index.
# - Dictionary values become the corresponding data.


# -------------------------
# Series Example: Cricketer Names
# -------------------------
cricketers_dict = {
    "p1": "Virat Kohli",
    "p2": "Sachin Tendulkar",
    "p3": "AB de Villiers",
    "p4": "Rohit Sharma",
    "p5": "Adam Gilchrist"
}

cricketers_series = pd.Series(cricketers_dict)
print(cricketers_series)


# -------------------------
# Indexing in Series
# Two ways to access Series elements:
# 1) Using label-based indexing
# 2) Using position-based indexing (integer location)
# -------------------------

# Access by position (0-based indexing)
# NOTE: Using cricketers_series[1] is deprecated due to ambiguity.
print(cricketers_series.iloc[1])    # Recommended: integer-location indexing

# Access by label (index name)
# For example: "p2"
print(cricketers_series["p2"])


# -------------------------
# Slicing in Series
# -------------------------

# Slice using integer-based position
print(cricketers_series[1:3])   # Returns elements at positions 1 and 2

# Slice using index labels — endpoint inclusive
print(cricketers_series["p2":"p3"])


# -------------------------
# Series Index and Values
# -------------------------
print(cricketers_series.index)   # Shows the index labels
print(cricketers_series.values)  # Underlying NumPy array of values


# -------------------------
# Sorting Series
# -------------------------
# Sort by values (default: ascending)
print(cricketers_series.sort_values())

# Sort in descending order
print(cricketers_series.sort_values(ascending=False))

# -----------------------------------------------------------------------------------------------------------------------------

#Data Frame
# -------------------------------------------------------------
# 1. Reading tabular data using pandas
# -------------------------------------------------------------

# Load data from CSV file.
# No extra library is needed for CSV files.
data_from_csv = pd.read_csv("Datasets/datasets/apple_stocks.csv")
print(data_from_csv)

# Load data from Excel file.
# Requires 'openpyxl' library installed.
data_from_excel = pd.read_excel("Datasets/datasets/automobile_camera.xlsx")
print(data_from_excel)


# -------------------------------------------------------------
# 2. Creating a DataFrame using a dictionary
# -------------------------------------------------------------

# Each key represents a column name,
# and each list represents column values.
# All lists must be of equal length.
df_dict = {
    'Year' : [1990, 1994, 1998, 2002],
    'Country' : ['Italy', 'USA', 'France', 'Japan'],
    'Winner' : ['Germany', 'Brazil', 'France', 'Brazil'],
    'GoalScored' : [115, 141, 171, 161]
}

print(pd.DataFrame(df_dict))


# -------------------------------------------------------------
# 3. Error demonstration using try–except
# -------------------------------------------------------------

try:
    # Here columns have unequal lengths.
    # 'GoalScored' has only 3 values, others have 4.
    # This will raise a ValueError.
    df_dict = {
        'Year' : [1990, 1994, 1998, 2002],
        'Country' : ['Italy', 'USA', 'France', 'Japan'],
        'Winner' : ['Germany', 'Brazil', 'France', 'Brazil'],
        'GoalScored' : [115, 141, 171]   # Mismatch
    }

    pd.DataFrame(df_dict)   # Error occurs here
except Exception as e:
    print(e)  # Print the exception message


# -------------------------------------------------------------
# 4. Creating DataFrame from Series
# -------------------------------------------------------------

# When creating a DataFrame using Series:
# - Series can have unequal lengths.
# - Missing values will be filled with NaN.
df_dict_udindex = {
    'Winner' : pd.Series(['Germany', 'Brazil', 'France']),
    'GoalScored' : pd.Series([115, 141, 171, 161])
}

print(pd.DataFrame(df_dict_udindex))


# -------------------------------------------------------------
# 5. Creating DataFrame from a list of tuples
# -------------------------------------------------------------

# Each tuple represents one row of the table.
df_lotuples = [
    (2002, 'Japan', 'Brazil', 161),
    (2006, 'Germany', 'Italy', 147),
    (2010, 'South Africa', 'Spain', 145),
    (2014, 'Brazil', 'Germany', 171)
]

# If no column names specified, pandas uses default numeric columns.
print(pd.DataFrame(df_lotuples))

# Same data but with column names provided.
fifa_df_lotuples = pd.DataFrame(
    df_lotuples,
    columns=["Year", "HostCountry", "Winner", "GoalScored"]
)

print(fifa_df_lotuples)


# -------------------------------------------------------------
# 6. Creating DataFrame from a list of dictionaries
# -------------------------------------------------------------

# Each dictionary represents a row.
# Keys become column names.
df_lodict = [
    {'year' : 2002, 'HostCountry' : 'Japan', 'Winner' : 'Brazil'},
    {'year' : 2006, 'HostCountry' : 'Germany', 'Winner' : 'Italy'},
    {'year' : 2010, 'HostCountry' : 'South Africa', 'Winner' : 'Spain'},
    {'year' : 2014, 'HostCountry' : 'Brazil', 'Winner' : 'Germany'},
]

print(pd.DataFrame(df_lodict))
