# Pandas: Why do we need it when we already have NumPy?
# -----------------------------------------------------
# NumPy arrays are excellent for numerical, homogeneous data (all values of the same type).
# However, real-world datasets—such as those in Excel sheets, CSVs, SQL tables—are typically
# *tabular* and *heterogeneous* (different column types: names, dates, numbers, categories).
#
# Pandas provides data structures (Series, DataFrame) that allow:
# - labeled rows and columns,
# - easier data cleaning,
# - handling of mixed datatypes,
# - loading/saving data from multiple file formats,
# - powerful indexing and slicing.
#
# In short: Pandas is designed for *data analysis*, while NumPy is designed for *numerical computation*.


import pandas as pd     # Pandas: handles structured/tabular data efficiently
import numpy as np      # NumPy: optimized for numerical, homogeneous data storage


# -----------------------------------------------------------------------------
# Pandas Data Structures
# 1) Series     -> 1-dimensional labeled array
# 2) DataFrame  -> 2-dimensional labeled table
# -----------------------------------------------------------------------------


# -------------------------
# Creating a Series from a list
# -------------------------
river = ['ganga', 'yamuna', 'neil', 'Tennessee', 'Brazos']
print(river, type(river))  # Normal Python list

# Convert list to Pandas Series
print(pd.Series(river))
# Note: Pandas automatically assigns integer index (0, 1, 2, ...)


# -------------------------
# Creating a Series from NumPy array
# -------------------------
print(pd.Series(np.random.randn(5)))
# Here, a Series is created from random numbers generated by NumPy.


# -------------------------
# Creating a Series from a Dictionary
# -------------------------
dic = {'a': 1, 'b': 2, 'c': 3}
print(pd.Series(dic))
# When using a dictionary:
# - Dictionary keys become the index.
# - Dictionary values become the corresponding data.


# -------------------------
# Series Example: Cricketer Names
# -------------------------
cricketers_dict = {
    "p1": "Virat Kohli",
    "p2": "Sachin Tendulkar",
    "p3": "AB de Villiers",
    "p4": "Rohit Sharma",
    "p5": "Adam Gilchrist"
}

cricketers_series = pd.Series(cricketers_dict)
print(cricketers_series)


# -------------------------
# Indexing in Series
# Two ways to access Series elements:
# 1) Using label-based indexing
# 2) Using position-based indexing (integer location)
# -------------------------

# Access by position (0-based indexing)
# NOTE: Using cricketers_series[1] is deprecated due to ambiguity.
print(cricketers_series.iloc[1])    # Recommended: integer-location indexing

# Access by label (index name)
# For example: "p2"
print(cricketers_series["p2"])


# -------------------------
# Slicing in Series
# -------------------------

# Slice using integer-based position
print(cricketers_series[1:3])   # Returns elements at positions 1 and 2

# Slice using index labels — endpoint inclusive
print(cricketers_series["p2":"p3"])


# -------------------------
# Series Index and Values
# -------------------------
print(cricketers_series.index)   # Shows the index labels
print(cricketers_series.values)  # Underlying NumPy array of values


# -------------------------
# Sorting Series
# -------------------------
# Sort by values (default: ascending)
print(cricketers_series.sort_values())

# Sort in descending order
print(cricketers_series.sort_values(ascending=False))

# -----------------------------------------------------------------------------------------------------------------------------
